import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Prowiz Analytics Portfolio",
  description: "Generated by create next app",
};

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
